### ISSUE TITLE
Background color blinking on mouse over

### ISSUE THREAD

**Issue by infinitalo** [lcagustini/tabivoro#4]

**Comment by lcagustini** [comment]
Fixed on commit 2c3509a.

**Comment by infinitalo** [comment]
I changed the old code so I'll reopen this, but I have an idea to fix this again AND improve performance.

So, my idea is:
Basically, we should stop calling `update` to redraw every row X times a second. Instead, we could only update the timer and reuse the same rows.
To do this, we should only add/remove rows when one of these happen:
- Tab is created
- Tab is updated
- Tab is replaced (same as updated but chrome calls a different function when a url is cached)
- Tab is closed

Luckily, we have a function for each of these, so it shouldn't be too hard.
This would stop blinking and save tons of time every time `update` is called.

**Comment by lcagustini** [comment]
Fixed on commit 336bf52.
